spring.application.name=bikes
# LOCALE config
spring.web.locale-resolver=fixed
spring.web.locale=pt_BR

# POSTGRES Config
spring.datasource.driverClassName=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/bikes
spring.datasource.username=postgres
spring.datasource.password=

# JPA
# exibe sql no log
spring.jpa.show-sql=true 
# exibe em uma única linha
spring.jpa.properties.hibernate.format_sql=false
# cria as tabelas a partir das classes entidades
spring.jpa.hibernate.ddl-auto=update

#SWAGGER
springdoc.swagger-ui.path=/docs-bikes.html
# Código gerado para acessar a documentação da API no Swagger UI: http://localhost:8080/docs-bikes.html
springdoc.api-docs.path=/docs-bikes
springdoc.packages-to-scan=br.edu.ifc.bikes.web.controller